#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("UMeng.Shares.Resource", IsApplication=false)]

namespace UMeng.Shares
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050001
			public static int umeng_socialize_color_group = 2131034113;
			
			// aapt resource value: 0x7f050000
			public static int umeng_socialize_comments_bg = 2131034112;
			
			// aapt resource value: 0x7f050004
			public static int umeng_socialize_divider = 2131034116;
			
			// aapt resource value: 0x7f05000b
			public static int umeng_socialize_edit_bg = 2131034123;
			
			// aapt resource value: 0x7f05000c
			public static int umeng_socialize_grid_divider_line = 2131034124;
			
			// aapt resource value: 0x7f050003
			public static int umeng_socialize_list_item_bgcolor = 2131034115;
			
			// aapt resource value: 0x7f050002
			public static int umeng_socialize_list_item_textcolor = 2131034114;
			
			// aapt resource value: 0x7f05000e
			public static int umeng_socialize_shareactivity = 2131034126;
			
			// aapt resource value: 0x7f05000f
			public static int umeng_socialize_shareactivitydefault = 2131034127;
			
			// aapt resource value: 0x7f050007
			public static int umeng_socialize_text_friends_list = 2131034119;
			
			// aapt resource value: 0x7f050008
			public static int umeng_socialize_text_share_content = 2131034120;
			
			// aapt resource value: 0x7f050005
			public static int umeng_socialize_text_time = 2131034117;
			
			// aapt resource value: 0x7f050006
			public static int umeng_socialize_text_title = 2131034118;
			
			// aapt resource value: 0x7f05000a
			public static int umeng_socialize_text_ucenter = 2131034122;
			
			// aapt resource value: 0x7f050009
			public static int umeng_socialize_ucenter_bg = 2131034121;
			
			// aapt resource value: 0x7f05000d
			public static int umeng_socialize_web_bg = 2131034125;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f060000
			public static int alphabet_size = 2131099648;
			
			// aapt resource value: 0x7f060001
			public static int umeng_socialize_pad_window_height = 2131099649;
			
			// aapt resource value: 0x7f060002
			public static int umeng_socialize_pad_window_width = 2131099650;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public static int umeng_socialize_back_icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public static int umeng_socialize_btn_bg = 2130837505;
			
			// aapt resource value: 0x7f020002
			public static int umeng_socialize_copy = 2130837506;
			
			// aapt resource value: 0x7f020003
			public static int umeng_socialize_copyurl = 2130837507;
			
			// aapt resource value: 0x7f020004
			public static int umeng_socialize_delete = 2130837508;
			
			// aapt resource value: 0x7f020005
			public static int umeng_socialize_edit_bg = 2130837509;
			
			// aapt resource value: 0x7f020006
			public static int umeng_socialize_fav = 2130837510;
			
			// aapt resource value: 0x7f020007
			public static int umeng_socialize_menu_default = 2130837511;
			
			// aapt resource value: 0x7f020008
			public static int umeng_socialize_more = 2130837512;
			
			// aapt resource value: 0x7f020009
			public static int umeng_socialize_qq = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public static int umeng_socialize_qzone = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public static int umeng_socialize_share = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public static int umeng_socialize_share_music = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public static int umeng_socialize_share_video = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public static int umeng_socialize_share_web = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public static int umeng_socialize_sina = 2130837519;
			
			// aapt resource value: 0x7f020010
			public static int umeng_socialize_wechat = 2130837520;
			
			// aapt resource value: 0x7f020011
			public static int umeng_socialize_wxcircle = 2130837521;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080009
			public static int progress_bar_parent = 2131230729;
			
			// aapt resource value: 0x7f08000a
			public static int root = 2131230730;
			
			// aapt resource value: 0x7f080000
			public static int socialize_image_view = 2131230720;
			
			// aapt resource value: 0x7f080001
			public static int socialize_text_view = 2131230721;
			
			// aapt resource value: 0x7f080004
			public static int umeng_back = 2131230724;
			
			// aapt resource value: 0x7f080012
			public static int umeng_del = 2131230738;
			
			// aapt resource value: 0x7f08000f
			public static int umeng_image_edge = 2131230735;
			
			// aapt resource value: 0x7f080005
			public static int umeng_share_btn = 2131230725;
			
			// aapt resource value: 0x7f080010
			public static int umeng_share_icon = 2131230736;
			
			// aapt resource value: 0x7f080006
			public static int umeng_socialize_follow = 2131230726;
			
			// aapt resource value: 0x7f080007
			public static int umeng_socialize_follow_check = 2131230727;
			
			// aapt resource value: 0x7f08000e
			public static int umeng_socialize_share_bottom_area = 2131230734;
			
			// aapt resource value: 0x7f08000c
			public static int umeng_socialize_share_edittext = 2131230732;
			
			// aapt resource value: 0x7f08000b
			public static int umeng_socialize_share_titlebar = 2131230731;
			
			// aapt resource value: 0x7f08000d
			public static int umeng_socialize_share_word_num = 2131230733;
			
			// aapt resource value: 0x7f080002
			public static int umeng_socialize_titlebar = 2131230722;
			
			// aapt resource value: 0x7f080003
			public static int umeng_title = 2131230723;
			
			// aapt resource value: 0x7f080011
			public static int umeng_web_title = 2131230737;
			
			// aapt resource value: 0x7f080008
			public static int webView = 2131230728;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public static int socialize_share_menu_item = 2130903040;
			
			// aapt resource value: 0x7f030001
			public static int umeng_socialize_oauth_dialog = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public static int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public static int Hello = 2130968576;
			
			// aapt resource value: 0x7f040013
			public static int umeng_example_home_btn_plus = 2130968595;
			
			// aapt resource value: 0x7f040016
			public static int umeng_socialize_cancel_btn_str = 2130968598;
			
			// aapt resource value: 0x7f040015
			public static int umeng_socialize_content_hint = 2130968597;
			
			// aapt resource value: 0x7f040018
			public static int umeng_socialize_female = 2130968600;
			
			// aapt resource value: 0x7f04001b
			public static int umeng_socialize_mail = 2130968603;
			
			// aapt resource value: 0x7f040019
			public static int umeng_socialize_male = 2130968601;
			
			// aapt resource value: 0x7f040017
			public static int umeng_socialize_send_btn_str = 2130968599;
			
			// aapt resource value: 0x7f04001a
			public static int umeng_socialize_share = 2130968602;
			
			// aapt resource value: 0x7f040003
			public static int umeng_socialize_sharetodouban = 2130968579;
			
			// aapt resource value: 0x7f040007
			public static int umeng_socialize_sharetolinkin = 2130968583;
			
			// aapt resource value: 0x7f040004
			public static int umeng_socialize_sharetorenren = 2130968580;
			
			// aapt resource value: 0x7f040002
			public static int umeng_socialize_sharetosina = 2130968578;
			
			// aapt resource value: 0x7f040005
			public static int umeng_socialize_sharetotencent = 2130968581;
			
			// aapt resource value: 0x7f040006
			public static int umeng_socialize_sharetotwitter = 2130968582;
			
			// aapt resource value: 0x7f04001d
			public static int umeng_socialize_sina = 2130968605;
			
			// aapt resource value: 0x7f04001c
			public static int umeng_socialize_sms = 2130968604;
			
			// aapt resource value: 0x7f040012
			public static int umeng_socialize_text_add_custom_platform = 2130968594;
			
			// aapt resource value: 0x7f04002f
			public static int umeng_socialize_text_alipay_key = 2130968623;
			
			// aapt resource value: 0x7f040033
			public static int umeng_socialize_text_dingding_key = 2130968627;
			
			// aapt resource value: 0x7f04000e
			public static int umeng_socialize_text_douban_key = 2130968590;
			
			// aapt resource value: 0x7f040035
			public static int umeng_socialize_text_dropbox_key = 2130968629;
			
			// aapt resource value: 0x7f040021
			public static int umeng_socialize_text_evernote_key = 2130968609;
			
			// aapt resource value: 0x7f040023
			public static int umeng_socialize_text_facebook_key = 2130968611;
			
			// aapt resource value: 0x7f040024
			public static int umeng_socialize_text_facebookmessager_key = 2130968612;
			
			// aapt resource value: 0x7f04002d
			public static int umeng_socialize_text_flickr_key = 2130968621;
			
			// aapt resource value: 0x7f04002a
			public static int umeng_socialize_text_foursquare_key = 2130968618;
			
			// aapt resource value: 0x7f040031
			public static int umeng_socialize_text_googleplus_key = 2130968625;
			
			// aapt resource value: 0x7f040026
			public static int umeng_socialize_text_instagram_key = 2130968614;
			
			// aapt resource value: 0x7f040030
			public static int umeng_socialize_text_kakao_key = 2130968624;
			
			// aapt resource value: 0x7f040020
			public static int umeng_socialize_text_laiwangdynamic_key = 2130968608;
			
			// aapt resource value: 0x7f04002c
			public static int umeng_socialize_text_line_key = 2130968620;
			
			// aapt resource value: 0x7f040029
			public static int umeng_socialize_text_linkedin_key = 2130968617;
			
			// aapt resource value: 0x7f040032
			public static int umeng_socialize_text_more_key = 2130968626;
			
			// aapt resource value: 0x7f040027
			public static int umeng_socialize_text_pinterest_key = 2130968615;
			
			// aapt resource value: 0x7f040028
			public static int umeng_socialize_text_pocket_key = 2130968616;
			
			// aapt resource value: 0x7f04000b
			public static int umeng_socialize_text_qq_key = 2130968587;
			
			// aapt resource value: 0x7f04000c
			public static int umeng_socialize_text_qq_zone_key = 2130968588;
			
			// aapt resource value: 0x7f04000d
			public static int umeng_socialize_text_renren_key = 2130968589;
			
			// aapt resource value: 0x7f04000a
			public static int umeng_socialize_text_sina_key = 2130968586;
			
			// aapt resource value: 0x7f040008
			public static int umeng_socialize_text_tencent_key = 2130968584;
			
			// aapt resource value: 0x7f04002e
			public static int umeng_socialize_text_tumblr_key = 2130968622;
			
			// aapt resource value: 0x7f040025
			public static int umeng_socialize_text_twitter_key = 2130968613;
			
			// aapt resource value: 0x7f040034
			public static int umeng_socialize_text_vkontakte_key = 2130968628;
			
			// aapt resource value: 0x7f040014
			public static int umeng_socialize_text_waitting_share = 2130968596;
			
			// aapt resource value: 0x7f040010
			public static int umeng_socialize_text_weixin_circle_key = 2130968592;
			
			// aapt resource value: 0x7f040011
			public static int umeng_socialize_text_weixin_fav_key = 2130968593;
			
			// aapt resource value: 0x7f04000f
			public static int umeng_socialize_text_weixin_key = 2130968591;
			
			// aapt resource value: 0x7f040009
			public static int umeng_socialize_text_wenxin_fav = 2130968585;
			
			// aapt resource value: 0x7f04002b
			public static int umeng_socialize_text_whatsapp_key = 2130968619;
			
			// aapt resource value: 0x7f040022
			public static int umeng_socialize_text_ydnote_key = 2130968610;
			
			// aapt resource value: 0x7f04001e
			public static int umeng_socialize_text_yixin_key = 2130968606;
			
			// aapt resource value: 0x7f04001f
			public static int umeng_socialize_text_yixincircle_key = 2130968607;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public static int ACPLDialog = 2131165184;
			
			// aapt resource value: 0x7f070006
			public static int Theme_UMDefault = 2131165190;
			
			// aapt resource value: 0x7f070005
			public static int Theme_UMDialog = 2131165189;
			
			// aapt resource value: 0x7f070002
			public static int umeng_socialize_action_bar_item_im = 2131165186;
			
			// aapt resource value: 0x7f070003
			public static int umeng_socialize_action_bar_item_tv = 2131165187;
			
			// aapt resource value: 0x7f070001
			public static int umeng_socialize_action_bar_itemlayout = 2131165185;
			
			// aapt resource value: 0x7f070007
			public static int umeng_socialize_divider = 2131165191;
			
			// aapt resource value: 0x7f070009
			public static int umeng_socialize_edit_padding = 2131165193;
			
			// aapt resource value: 0x7f070008
			public static int umeng_socialize_list_item = 2131165192;
			
			// aapt resource value: 0x7f070004
			public static int umeng_socialize_popup_dialog = 2131165188;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
