#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("BaseAdapter.Resource", IsApplication=false)]

namespace BaseAdapter
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public static int layoutManager = 2130771968;
			
			// aapt resource value: 0x7f010002
			public static int reverseLayout = 2130771970;
			
			// aapt resource value: 0x7f010001
			public static int spanCount = 2130771969;
			
			// aapt resource value: 0x7f010003
			public static int stackFromEnd = 2130771971;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f040003
			public static int def_height = 2130968579;
			
			// aapt resource value: 0x7f040005
			public static int dp_10 = 2130968581;
			
			// aapt resource value: 0x7f040004
			public static int dp_4 = 2130968580;
			
			// aapt resource value: 0x7f040006
			public static int dp_40 = 2130968582;
			
			// aapt resource value: 0x7f040007
			public static int dp_72 = 2130968583;
			
			// aapt resource value: 0x7f040000
			public static int item_touch_helper_max_drag_scroll_per_frame = 2130968576;
			
			// aapt resource value: 0x7f040001
			public static int item_touch_helper_swipe_escape_max_velocity = 2130968577;
			
			// aapt resource value: 0x7f040002
			public static int item_touch_helper_swipe_escape_velocity = 2130968578;
			
			// aapt resource value: 0x7f040008
			public static int sp_12 = 2130968584;
			
			// aapt resource value: 0x7f040009
			public static int sp_14 = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public static int sp_16 = 2130968586;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public static int sample_footer_loading = 2130837504;
			
			// aapt resource value: 0x7f020001
			public static int sample_footer_loading_progress = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050004
			public static int BaseQuickAdapter_databinding_support = 2131034116;
			
			// aapt resource value: 0x7f050003
			public static int BaseQuickAdapter_dragging_support = 2131034115;
			
			// aapt resource value: 0x7f050002
			public static int BaseQuickAdapter_swiping_support = 2131034114;
			
			// aapt resource value: 0x7f050001
			public static int BaseQuickAdapter_viewholder_support = 2131034113;
			
			// aapt resource value: 0x7f050000
			public static int item_touch_helper_previous_elevation = 2131034112;
			
			// aapt resource value: 0x7f05000a
			public static int load_more_load_end_view = 2131034122;
			
			// aapt resource value: 0x7f050008
			public static int load_more_load_fail_view = 2131034120;
			
			// aapt resource value: 0x7f050005
			public static int load_more_loading_view = 2131034117;
			
			// aapt resource value: 0x7f050006
			public static int loading_progress = 2131034118;
			
			// aapt resource value: 0x7f050007
			public static int loading_text = 2131034119;
			
			// aapt resource value: 0x7f050009
			public static int tv_prompt = 2131034121;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public static int quick_view_load_more = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060000
			public static int app_name = 2131099648;
			
			// aapt resource value: 0x7f060003
			public static int load_end = 2131099651;
			
			// aapt resource value: 0x7f060002
			public static int load_failed = 2131099650;
			
			// aapt resource value: 0x7f060001
			public static int loading = 2131099649;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] RecyclerView = new int[] {
					16842948,
					16842993,
					2130771968,
					2130771969,
					2130771970,
					2130771971};
			
			// aapt resource value: 1
			public static int RecyclerView_android_descendantFocusability = 1;
			
			// aapt resource value: 0
			public static int RecyclerView_android_orientation = 0;
			
			// aapt resource value: 2
			public static int RecyclerView_layoutManager = 2;
			
			// aapt resource value: 4
			public static int RecyclerView_reverseLayout = 4;
			
			// aapt resource value: 3
			public static int RecyclerView_spanCount = 3;
			
			// aapt resource value: 5
			public static int RecyclerView_stackFromEnd = 5;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
